### ISSUE TITLE
TODO's for major version

### ISSUE THREAD

**Issue by Groostav** [Groostav/sojourn-CVG#1]
Items to be completed

- [ ] weighted scheduler to pick strategies that generate points
- [ ] break problem down by independence, unlreated constraints solved separately
- [ ] sum and prod
- [ ] other functions 
- [ ] handle `UNKNOWN` status properly
